# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regression_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(9, 35, 634, 741))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 610, 690))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.radioButtonClase = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButtonClase.setGeometry(QtCore.QRect(9, 9, 140, 23))
        self.radioButtonClase.setChecked(True)
        self.radioButtonClase.setObjectName("radioButtonClase")
        self.radioButtonFile = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButtonFile.setGeometry(QtCore.QRect(9, 38, 123, 23))
        self.radioButtonFile.setObjectName("radioButtonFile")
        self.radioButtonManual = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButtonManual.setGeometry(QtCore.QRect(10, 110, 227, 23))
        self.radioButtonManual.setObjectName("radioButtonManual")
        self.tableDatos = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tableDatos.setGeometry(QtCore.QRect(160, 190, 231, 281))
        self.tableDatos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableDatos.setRowCount(1)
        self.tableDatos.setColumnCount(2)
        self.tableDatos.setObjectName("tableDatos")
        item = QtWidgets.QTableWidgetItem()
        self.tableDatos.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDatos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDatos.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableDatos.setItem(0, 1, item)
        self.pushButtonClasificar = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonClasificar.setGeometry(QtCore.QRect(0, 490, 541, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonClasificar.setFont(font)
        self.pushButtonClasificar.setObjectName("pushButtonClasificar")
        self.labelRes = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelRes.setGeometry(QtCore.QRect(0, 520, 551, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelRes.setFont(font)
        self.labelRes.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRes.setObjectName("labelRes")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 141, 17))
        self.label_7.setObjectName("label_7")
        self.spinBoxNumeroPatrones = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBoxNumeroPatrones.setGeometry(QtCore.QRect(180, 140, 48, 26))
        self.spinBoxNumeroPatrones.setMinimum(1)
        self.spinBoxNumeroPatrones.setObjectName("spinBoxNumeroPatrones")
        self.label_path = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_path.setGeometry(QtCore.QRect(30, 70, 411, 17))
        self.label_path.setText("")
        self.label_path.setObjectName("label_path")
        self.pushButtonBrowse = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonBrowse.setGeometry(QtCore.QRect(450, 70, 89, 25))
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.scrollArea_2, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 610, 690))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.formLayout_6 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_8)
        self.formLayout_6.setObjectName("formLayout_6")
        self.lawImage_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.lawImage_2.setText("")
        self.lawImage_2.setObjectName("lawImage_2")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lawImage_2)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_14)
        self.imagenTodos = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.imagenTodos.setObjectName("imagenTodos")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.imagenTodos)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.data = QtWidgets.QLabel(self.scrollAreaWidgetContents_8)
        self.data.setText("")
        self.data.setObjectName("data")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.data)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_8)
        self.gridLayout_2.addWidget(self.scrollArea_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 0, 621, 651))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 619, 649))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_3)
        self.formLayout.setObjectName("formLayout")
        self.linealImage = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.linealImage.setText("")
        self.linealImage.setObjectName("linealImage")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.linealImage)
        self.label_MSE_lineal = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_MSE_lineal.setFont(font)
        self.label_MSE_lineal.setObjectName("label_MSE_lineal")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_MSE_lineal)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_4.setGeometry(QtCore.QRect(0, 0, 621, 651))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 619, 649))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_8)
        self.label_MSE_Exp = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_MSE_Exp.setFont(font)
        self.label_MSE_Exp.setObjectName("label_MSE_Exp")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_MSE_Exp)
        self.expImage = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.expImage.setText("")
        self.expImage.setObjectName("expImage")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.expImage)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.expImage_log = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.expImage_log.setText("")
        self.expImage_log.setObjectName("expImage_log")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.expImage_log)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea_5.setGeometry(QtCore.QRect(0, 0, 621, 651))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 619, 649))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.formLayout_4 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_6)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lawImage = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lawImage.setText("")
        self.lawImage.setObjectName("lawImage")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lawImage)
        self.label_MSE_law = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_MSE_law.setFont(font)
        self.label_MSE_law.setObjectName("label_MSE_law")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_MSE_law)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_10)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lawImage_log = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.lawImage_log.setText("")
        self.lawImage_log.setObjectName("lawImage_log")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lawImage_log)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_6)
        self.scrollArea_6.setGeometry(QtCore.QRect(0, 0, 621, 651))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 619, 649))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.formLayout_5 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_7)
        self.formLayout_5.setObjectName("formLayout_5")
        self.poliImage = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        self.poliImage.setText("")
        self.poliImage.setObjectName("poliImage")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.poliImage)
        self.label_MSE_poli = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_MSE_poli.setFont(font)
        self.label_MSE_poli.setObjectName("label_MSE_poli")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_MSE_poli)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_11)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Regresiones"))
        self.radioButtonClase.setText(_translate("MainWindow", "Ejercicio de clase"))
        self.radioButtonFile.setText(_translate("MainWindow", "Cargar archivo"))
        self.radioButtonManual.setText(_translate("MainWindow", "Introducción manual de datos"))
        item = self.tableDatos.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableDatos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableDatos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        __sortingEnabled = self.tableDatos.isSortingEnabled()
        self.tableDatos.setSortingEnabled(False)
        item = self.tableDatos.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableDatos.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        self.tableDatos.setSortingEnabled(__sortingEnabled)
        self.pushButtonClasificar.setText(_translate("MainWindow", "Hacer regresiones"))
        self.labelRes.setText(_translate("MainWindow", "Mejor regresión"))
        self.label_7.setText(_translate("MainWindow", "Número de patrones"))
        self.pushButtonBrowse.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Datos"))
        self.label_20.setText(_translate("MainWindow", "Gráfico de los puntos"))
        self.label_14.setText(_translate("MainWindow", "Descripción de los datos"))
        self.imagenTodos.setText(_translate("MainWindow", "graficoPuntos"))
        self.label_15.setText(_translate("MainWindow", "Datos estádisticos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Descrición de datos"))
        self.label_MSE_lineal.setText(_translate("MainWindow", "MSE: "))
        self.label_6.setText(_translate("MainWindow", "Regresión lineal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Lineal"))
        self.label_8.setText(_translate("MainWindow", "Regresión exponencial"))
        self.label_MSE_Exp.setText(_translate("MainWindow", "MSE: "))
        self.label_2.setText(_translate("MainWindow", "Escala logaritmica"))
        self.label_12.setText(_translate("MainWindow", "Escala líneal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Exp"))
        self.label_MSE_law.setText(_translate("MainWindow", "MSE: "))
        self.label_10.setText(_translate("MainWindow", "Regresión ley de potencias"))
        self.label_3.setText(_translate("MainWindow", "Escala líneal"))
        self.label_13.setText(_translate("MainWindow", "Escala logaritmica"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Ley potencias"))
        self.label_MSE_poli.setText(_translate("MainWindow", "MSE: "))
        self.label_11.setText(_translate("MainWindow", "Regresión polinomial"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Polinomial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
